# Generated by Django 3.2.4 on 2021-10-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_videononpublishedproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='publish_timestamp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='state',
            field=models.CharField(choices=[('PU', 'Published'), ('DR', 'Draft')], default='DR', max_length=2),
        ),
    ]
